version: '3.8'

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: stock_analysis_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dev_root_password
      MYSQL_DATABASE: stock_analysis_dev
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stock_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis 缓存服务
  redis:
    image: redis:7-alpine
    container_name: stock_analysis_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stock_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

  # 后端 FastAPI 服务
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_analysis_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://dev_user:dev_password@mysql:3306/stock_analysis_dev
      - REDIS_URL=redis://redis:6379
      - DEBUG=True
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    networks:
      - stock_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 10s
      retries: 5

  # 前端 React 服务 (管理端)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock_analysis_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_ENVIRONMENT=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - stock_network

  # 客户端 React 服务 (用户端)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: stock_analysis_client
    restart: unless-stopped
    ports:
      - "8006:8006"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_ENVIRONMENT=development
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - stock_network

  # Nginx 反向代理 (可选，生产环境使用)
  nginx:
    image: nginx:alpine
    container_name: stock_analysis_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - client
      - backend
    networks:
      - stock_network
    profiles:
      - production

# 网络配置
networks:
  stock_network:
    driver: bridge

# 数据卷配置
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  backend_uploads:
    driver: local
  backend_logs:
    driver: local